daily_checkin/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(),
          name='login'),
    path('main/', include('main.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView

app_name = 'main'


urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('daily/emotion/choose/', views.DailyEmotionMoodChooseView.as_view(),
         name='daily_emotion_mood_choose'),
    path('daily/emotion/resonate/<mood>', views.DailyEmotionResonateChooseView.as_view(),
         name='daily_emotion_resonate_choose'),
    path('daily/emotion/reason/', views.DailyEmotionReasonChooseView.as_view(),
         name='daily_emotion_reason'),
    path('daily/emotion/done/', views.DailyEmotionDone.as_view(),
         name='daily_emotion_done'),
    path('daily/emotion/save/', views.DailyEmotionSaveView.as_view(),
         name='daily_emotion_save'),
    path('my/to/do', views.MyToDoListView.as_view(),
         name='my_todo'),
    path('my/todo/add', views.MyToDoAddView.as_view(),
         name='my_todo_add'),
    path('my/todo/done', views.MyToDoDoneView.as_view(),
         name='my_todo_done'),
    path('diary/save', views.DiarySaveView.as_view(),
         name='diary_save'),
    path('my/diary', views.MyDiaryView.as_view(),
         name='my_diary'),
    path('register/', views.RegistrationView.as_view(),
         name='register'),
    path('profile/', views.ProfileView.as_view(),
         name='profile'),
    path('user/update/', views.UserUpdateView.as_view(),
         name='user_update'),
    path('password-change/', views.CustomPasswordChangeView.as_view(template_name='password_change.html'), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name='password_change_done'),
    path('start-test/<pk>', views.StartTestView.as_view(), name='start_test'),
    path('get-question/', views.GetQuestionView.as_view(), name='get_question'),
    path('submit-answer/', views.SubmitAnswerView.as_view(), name='submit_answer'),
    path('test-completed/', views.IsTestCompletedView.as_view(), name='test_completed'),
    path('delete/user/<pk>', views.DleteUserView.as_view(), name='delete_user'),
    
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='media', default='assets/img/smile1.png')

class EmotionsResonate(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class DailyEmotion(models.Model):
    date = models.DateField(auto_now_add=True)
    mood = models.CharField(max_length=100, blank=True, null=True)
    reason = models.TextField(blank=True, null=True)
    emotions_resonate = models.ManyToManyField('EmotionsResonate')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.mood

class ToDo(models.Model):
    title = models.CharField(max_length=200)
    def __str__(self):
        return self.title

class MyToDo(models.Model):
    todo = models.ManyToManyField('ToDo')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

from datetime import date
class MyToDoDone(models.Model):
    date = models.DateField(default=date.today)
    my_todo = models.ManyToManyField('ToDo')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Diary(models.Model):
    STATUS_CHOICES = (
        (1, 'Positive'),
        (2, 'Negative'),
        (3, 'Sleep'),
        (4, 'Date')
    )
    title = models.CharField(max_length=200)
    text = models.TextField()
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)

class Question(models.Model):
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.text

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField(max_length=200)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    diary = models.ForeignKey(Diary, on_delete=models.CASCADE, related_name='diaries', null=True, blank=True)

templates/base.html
<!doctype html> {% load static %}
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#000000">
    <title></title>
    <meta name="description" content="Mobilekit HTML Mobile UI Kit">
    <meta name="keywords" content="bootstrap 5, mobile template, cordova, phonegap, mobile, html" />
    <link rel="icon" type="image/png" href="assets/img/favicon.png" sizes="32x32">
    <link rel="apple-touch-icon" sizes="180x180" href="assets/img/icon/192x192.png">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="manifest" href="__manifest.json">
</head>

<body class="" style="background-color: #FFFFF0">




    <!-- App Capsule -->
    <div id="" class="pt-0">

        {% block content %} {% endblock %}

        <div class="appBottomMenu">
            <a href="{%  url 'main:index' %}" class="item">
                <div class="col">
                    <ion-icon name="file-tray-full-outline" role="img" class="md hydrated" aria-label="file tray full outline"></ion-icon>
                    <strong>Home</strong>
                </div>
            </a>
            <a href="{% url 'main:my_todo_done' %}" class="item">
                <div class="col">
                    <ion-icon name="calendar-outline" role="img" class="md hydrated" aria-label="calendar outline"></ion-icon>
                    <strong>Calendar</strong>
                </div>
            </a>
            <a href="{% url 'main:diary_save' %}" class="item">
                <div class="col">
                    <div class="action-button large" style="background-color: #30C08B">
                        <ion-icon name="add-outline" role="img" class="md hydrated" aria-label="add outline"></ion-icon>
                    </div>
                </div>
            </a>
            <a href="{% url 'main:my_diary' %}" class="item">
                <div class="col">
                    <div class="col">
                        <ion-icon name="browsers-outline"></ion-icon>
                    </div>
                    <strong>My diary</strong>
                </div>
            </a>
            <a href="{% url 'main:profile' %}" class="item">
                <div class="col">
                    <ion-icon name="people-outline" role="img" class="md hydrated" aria-label="people outline"></ion-icon>
                    <strong>Profile</strong>
                </div>
            </a>
        </div>
    </div>
    <!-- * App Capsule -->



    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <!-- Splide -->
    <script src="{% static 'assets/js/plugins/splide/splide.min.js' %}"></script>
    <!-- ProgressBar js -->
    <script src="{% static 'assets/js/plugins/progressbar-js/progressbar.min.js' %}"></script>
     <script src="{% static 'assets/js/lib/bootstrap.min.js' %}"></script>
    

</body>

</html>

templates/calendar.html
{% extends 'base.html' %}
{% load my_tags %}
{% load static %}
{% block content %}
<script src="{% static 'assets/js/lib/bootstrap.min.js' %}"></script>
<div class="appHeader " style="background-color: transparent;box-shadow: none;">
    <div class="left">
        <a href="{% url 'main:index' %}" class="headerButton goBack">
            <ion-icon name="chevron-back-outline" role="img" class="md hydrated" aria-label="chevron back outline"></ion-icon>
        </a>
    </div>
    <div class="pageTitle">
        Calendar
    </div>
    <div class="right">
        
    </div>
</div>
<!-- * App Header -->
<div class="section full" style="margin-top: 55px !important">
    <div class="wide-block pt-2 pb-2" style="background-color: transparent;">

        <ul class="nav nav-tabs capsuled" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-bs-toggle="tab" href="#home" role="tab" aria-selected="true">
                    Daily check in
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#profile" role="tab" aria-selected="false">
                    Habits
                </a>
            </li>
        </ul>
        <div class="tab-content mt-2">
            <div class="tab-pane fade active show" id="home" role="tabpanel">
                Last 7 days your mood was: <br>
                <div style="display: flex;margin-bottom: 20px;margin-top: 20px;overflow-y: scroll;justify-content: space-between;">
                    <div style="background-color: #EFE0D5;border-radius: 10px;padding: 5px; text-align: center;margin-right: 5px;">
                        <img src="{% static 'assets/img/image 17.png' %}" style="width: 65px;">
                        <span style="display: block;font-size: 14px">{{happy_count}}</span> happy
                    </div>
                    <div style="background-color: #EFE0D5;border-radius: 10px;padding: 5px; text-align: center;margin-right: 5px;">
                        <img src="{% static 'assets/img/image 19.png' %}" style="width: 65px;">
                        <span style="display: block;font-size: 14px">{{sad_count}}</span>  Sad
                    </div>
                    <div style="background-color: #EFE0D5;border-radius: 10px;padding: 5px; text-align: center;margin-right: 5px;">
                        <img src="{% static 'assets/img/image 20.png' %}" style="width: 65px;">
                        <span style="display: block;font-size: 14px">{{ok_count}}</span>  Ok
                    </div>
                    <div style="background-color: #EFE0D5;border-radius: 10px;padding: 5px; text-align: center;margin-right: 5px;">
                        <img src="{% static 'assets/img/image 21.png' %}" style="width: 65px;">
                        <span style="display: block;font-size: 14px">{{pretty_good_count}}</span>  Pretty Good
                    </div>
                    <div style="background-color: #EFE0D5;border-radius: 10px;padding: 5px; text-align: center;margin-right: 5px;">
                        <img src="{% static 'assets/img/image 23.png' %}" style="width: 65px;">
                       <span style="display: block;font-size: 14px"> {{awful_count}}</span>  Awful
                    </div>
                </div>
                
                <canvas id="myChart" width="500" height="300"></canvas>

            </div>
            <div class="tab-pane fade" id="profile" role="tabpanel">
                <div class="section-title">Done list </div>
                {% for todo_done in todo_done_list %}
                
                {% for todo in todo_done.my_todo.all %}
                <div style="background: rgba(48, 192, 139, 0.15);border: 1px solid #30C08B;border-radius: 15px;height: 91px; padding: 17px 12px; margin-bottom: 15px">
                    <span style="display: block;">{{todo_done.date}}</span>
                    {{todo.title}}
                </div>
                {% endfor %}
                {% endfor %}
            </div>
        </div>

    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<br><br><br>
<!-- <a class="btn btn-secondary" href="{% url 'main:my_todo_done' %}">Daily check in</a> <a class="btn btn-success" href="/main/my/to/do">Habits</a>
<br><br><br>

<canvas id="myChart" width="500" height="300"></canvas>

<div class="appHeader bg-primary scrolled">
    <div class="left">
        <a href="{% url 'main:index' %}" class="headerButton goBack">
            <ion-icon name="chevron-back-outline" role="img" class="md hydrated" aria-label="chevron back outline"></ion-icon>
        </a>
    </div>
    <div class="pageTitle">Calendar</div>
    <div class="right">
    </div>
</div>
<div id="appCapsule">
	<div class="section full mt-1">
	    <div class="section-title">Done list 
	    	
	    </div>
	    {% for todo_done in todo_done_list %}
	    <span style="margin-left: 15px">{{todo_done.date}}</span>
	    {% for todo in todo_done.my_todo.all %}
	    <ul class="listview simple-listview">
            <li> {{todo.title}}</li>
        </ul>
        {% endfor %}
        {% endfor %}
	</div>
</div> -->
<script>
$(document).ready(function(){
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Happy', 'Ok', 'Sad', 'Pretty Good', 'Awful'],
            datasets: [{
                label: 'Your activity level!',
                data: [{{happy_count}}, {{ok_count}}, {{sad_count}}, {{pretty_good_count}}, {{awful_count}}],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
});
</script>
{% endblock %}

templates/done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="appHeader " style="background-color: transparent;box-shadow: none;">
    <div class="left">
        <a href="{% url 'main:index' %}" class="headerButton goBack">
            <ion-icon name="chevron-back-outline" role="img" class="md hydrated" aria-label="chevron back outline"></ion-icon>
        </a>
    </div>
    <div class="pageTitle">
     Done
    </div>
    <div class="right">
        
    </div>
</div>
<div class="section full" style="margin-top: 55px !important">
    <div class="wide-block pt-2 pb-2" style="background-color: transparent;">
        <div class="section-title">Well Done! You managed to fill another check in.</div>
	    <div class="pt-2 pb-2 text-center">
	    	<img src="{% static 'assets/img/image24.png' %}">
	    	<a href="{% url 'main:index' %}"  class="btn btn-secondary" style="display: block;background-color: #30C08B !important;border-color:#30C08B !important ">
				
				GO HOME
			</a>
	    </div>
    </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- App Header -->
    <div class="appHeader bg-primary scrolled">
        <div class="left">
            <a href="index.html#" class="headerButton" data-bs-toggle="offcanvas" data-bs-target="#sidebarPanel">
                <ion-icon name="menu-outline"></ion-icon>
            </a>
        </div>
        <div class="pageTitle">
            Diary
        </div>
        <div class="right">
            <a href="index.html#" class="headerButton toggle-searchbox">
                <ion-icon name="search-outline"></ion-icon>
            </a>
        </div>
    </div>
    <!-- * App Header -->

    <!-- App Capsule -->
    <div id="appCapsule">

        <div class="header-large-title">
            <h1 class="title">Diary</h1>
        </div>

        
        <div class="section mt-3">
            <!-- carousel multiple -->
            <div class="" style="display: flex; flex-direction: row; justify-content: space-between;">
                <div class="" style="width: 48%">
                    <div class="card text-center" style="background-color: #EFE0D5">
                        <img src="{% static 'assets/img/home1.png' %}" style="width: 75px; margin:13px auto" class="card-img-top" alt="image">
                        <div class="card-body pt-0">
                            <a href="{% url 'main:daily_emotion_mood_choose' %}" style="color: #000;font-size: 20px; font-weight: 600" class="mb-0">Daily check-in</a>
                        </div>
                    </div>
                </div>
                <div class="" style="width: 48%">
                    <div class="card text-center" style="background-color: #EFE0D5">
                        <img src="{% static 'assets/img/home2.png' %}" style="width: 75px; margin:13px auto" class="card-img-top" alt="image">
                        <div class="card-body pt-0">
                            <a href="{% url 'main:my_todo' %}" style="color: #000;font-size: 20px; font-weight: 600" class="mb-0">To-do</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="section mt-3 mb-3">
                <div class="content-box" style="display: flex;justify-content: space-between;align-items: center; background: #30C08B;padding: 15px;border-radius: 12px;display: flex;">
                    <div class="content color-white content-left">
                        <h5 class="title-item color-white" style="font-weight: 500;color: #383e50;margin-bottom: 5px;white-space: nowrap;overflow: hidden;text-overflow: ellipsis; color: #fff;font-size: 21px">Another day, another story!</h5>
                    </div>
                    <div class="content content-right" style="width: 40px;height: 40px;font-size: 22px;padding: 0;background: #30C08B;border-radius: 8px;padding: 0 15px;height: 45px;line-height: 45px;font-size: 14px;font-weight: 500;color: #fff;text-transform: none;">
                        <a class="button button-icon-large" class="btn btn-secondary" href="{% url 'main:daily_emotion_mood_choose' %}" style="font-size:24px; color: #fff">
                           >
                        </a>
                    </div>
                </div>   
        </div>
       

        <div class="section mt-3 mb-3">
            <div class="header-large-title">
                <h4 class="subtitle" style="font-size: 23px;color: #000;font-weight: 600;margin-bottom: 9px;">Mood Story</h4>
            </div>
            <div class="row">
            	{% for daily_emotion in daily_emotions %}
                <div class="col-sm-12" style="margin-bottom: 10px;">
                    <div class="card" >
                        <div class="card-body" style="display: flex; flex-direction: row; align-items: center;text-align: left;">
                            <div style="margin-right: 15px;">
                                {% if daily_emotion.mood == 'Sad' %}
                                <img src="{% static 'assets/img/image 19.png' %}" style="width: 75px;">
                                {% elif daily_emotion.mood == 'happy' %}
                                <img src="{% static 'assets/img/image 17.png' %}" style="width: 75px;">
                                {% elif daily_emotion.mood == 'Ok' %}
                                <img src="{% static 'assets/img/image 20.png' %}" style="width: 75px;">
                                {% elif daily_emotion.mood == 'Pretty Good' %}
                                <img src="{% static 'assets/img/image 21.png' %}" style="width: 75px;">
                                {% elif daily_emotion.mood == 'Awful' %}
                                <img src="{% static 'assets/img/image 23.png' %}" style="width: 75px;">
                                {% endif %}
                            </div>
                            <div>
                                <h6 class="second-title" style="font-weight: 600; font-size: 15px;">{{ daily_emotion.date|date:"D"|title }}
                                </h6>
                                <span>{{ daily_emotion.mood }}, {{ daily_emotion.reason|slice:":10" }}...</span>
                                <p>{{ daily_emotion.date|date:"d.m" }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>


        <!-- app footer -->
        <div class="appFooter">
            <div class="footer-title">
                Copyright © <span class="yearNow"></span>. All Rights Reserved.
            </div>

            <div class="mt-2">
                <a href="index.html#" class="btn btn-icon btn-sm btn-facebook">
                    <ion-icon name="logo-facebook"></ion-icon>
                </a>
                <a href="index.html#" class="btn btn-icon btn-sm btn-twitter">
                    <ion-icon name="logo-twitter"></ion-icon>
                </a>
                <a href="index.html#" class="btn btn-icon btn-sm btn-linkedin">
                    <ion-icon name="logo-linkedin"></ion-icon>
                </a>
                <a href="index.html#" class="btn btn-icon btn-sm btn-instagram">
                    <ion-icon name="logo-instagram"></ion-icon>
                </a>
                <a href="index.html#" class="btn btn-icon btn-sm btn-whatsapp">
                    <ion-icon name="logo-whatsapp"></ion-icon>
                </a>
                <a href="index.html#" class="btn btn-icon btn-sm btn-secondary goTop">
                    <ion-icon name="arrow-up-outline"></ion-icon>
                </a>
            </div>

        </div>
        <!-- * app footer -->

    </div>
    <!-- * App Capsule -->

    <div class="appBottomMenu">
        <a href="{%  url 'main:index' %}" class="item">
            <div class="col">
                <ion-icon name="file-tray-full-outline" role="img" class="md hydrated" aria-label="file tray full outline"></ion-icon>
                <strong>Home</strong>
            </div>
        </a>
        <a href="{% url 'main:my_todo_done' %}" class="item active">
            <div class="col">
                <ion-icon name="calendar-outline" role="img" class="md hydrated" aria-label="calendar outline"></ion-icon>
                <strong>Calendar</strong>
            </div>
        </a>
        <a href="{% url 'main:diary_save' %}" class="item">
            <div class="col">
                <div class="action-button large" style="background-color: #30C08B">
                    <ion-icon name="add-outline" role="img" class="md hydrated" aria-label="add outline"></ion-icon>
                </div>
            </div>
        </a>
        <a href="{% url 'main:my_diary' %}" class="item">
            <div class="col">
                <div class="col">
                    <ion-icon name="browsers-outline"></ion-icon>
                </div>
                <strong>My diary</strong>
            </div>
        </a>
        <a href="{% url 'main:profile' %}" class="item">
            <div class="col">
                <ion-icon name="people-outline" role="img" class="md hydrated" aria-label="people outline"></ion-icon>
                <strong>Profile</strong>
            </div>
        </a>
    </div>
  
    <!-- App Sidebar -->
    <div class="offcanvas offcanvas-start" tabindex="-1" id="sidebarPanel">
        <div class="offcanvas-body">
            <!-- profile box -->
            <div class="profileBox">
                <div class="in">
                    <strong>{{ request.user }}</strong>
                    </div>
                </div>
                <a href="index.html#" class="close-sidebar-button" data-bs-dismiss="offcanvas">
                    <ion-icon name="close"></ion-icon>
                </a>
            </div>
            <!-- * profile box -->

            <ul class="listview flush transparent no-line image-listview mt-2">
                <li>
                    <a href="{%  url 'main:index' %}" class="item">
                        <div class="icon-box bg-primary">
                            <ion-icon name="home-outline"></ion-icon>
                        </div>
                        <div class="in">
                            Home
                        </div>
                    </a>
                </li>
                <li>
                    <a href="{% url 'main:my_todo' %}" class="item">
                        <div class="icon-box bg-primary">
                            <ion-icon name="calendar-outline"></ion-icon>
                        </div>
                        <div class="in">
                            Calendar
                        </div>
                    </a>
                </li>
                <li>
                    <a href="{% url 'login' %}" class="item">
                        <div class="icon-box bg-primary">
                            <ion-icon name="browsers-outline"></ion-icon>
                        </div>
                        <div class="in">
                            Logout
                        </div>
                    </a>
                </li>
               
            </ul>

            
        </div>
        <!-- sidebar buttons -->
        <div class="sidebar-buttons">
            <a href="index.html#" class="button">
                <ion-icon name="person-outline"></ion-icon>
            </a>
            
            <a href="index.html#" class="button">
                <ion-icon name="log-out-outline"></ion-icon>
            </a>
        </div>
        <!-- * sidebar buttons -->
    </div>
    <!-- * App Sidebar -->
<!-- <a href="{% url 'main:daily_emotion_mood_choose' %}">+ Another day, another story!</a><br><br>
<a href="{% url 'main:my_todo' %}">To-Do</a>
 -->
{% endblock %}

templates/my_todo.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="appHeader bg-primary text-light">
    <div class="left">
        <a href="{% url 'main:index' %}" class="headerButton goBack">
            <ion-icon name="chevron-back-outline" role="img" class="md hydrated" aria-label="chevron back outline"></ion-icon>
        </a>
    </div>
    <div class="pageTitle">Add To-Do</div>
    <div class="right">
    </div>
</div>
<div id="appCapsule">
	<div class="section full mt-1">
	    <div class="section-title">Add To-Do
	    	<a href="{% url 'main:my_todo_add' %}" class="btn btn-success me-1 mb-1">+</a>
	    </div>
	    <div class="wide-block pt-2 pb-2">
	    	<form action="{% url 'main:my_todo_done' %}" method="post">
			  {% csrf_token %}
			  {% for todo in my_todo.todo.all %}
			  <input type="checkbox" name="todo_list[]" value="{{todo.id|json_encode}}" {% is_my_todo_done_checked todo.id request.user %}>{{todo.title}}<br>
			  {% endfor %}
			  <input type="submit" class="btn btn-primary me-1 mb-1" value="SAVE">
			</form>
	    </div>
	</div>
</div>
{% endblock %}

templates/my_todo_add.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="appHeader bg-primary text-light">
    <div class="left">
        <a href="{% url 'main:index' %}" class="headerButton goBack">
            <ion-icon name="chevron-back-outline" role="img" class="md hydrated" aria-label="chevron back outline"></ion-icon>
        </a>
    </div>
    <div class="pageTitle">To-Do</div>
    <div class="right">
    </div>
</div>
<div id="appCapsule">
	<div class="section full mt-1">
	    <div class="section-title">To-Do
	    	
	    </div>
	    <div class="wide-block pt-2 pb-2">
	    	<form action="{% url 'main:my_todo_add' %}" method="POST">
			    {% csrf_token %}
			    {% for todo in todo_list %}
			    <input type="checkbox" name="todo_list[]" value="{{todo.id|json_encode}}" {% is_todo_checked todo.id request.user %}>{{todo.title}}<br>
			    {% endfor %}
			    <input type="submit" class="btn btn-primary me-1 mb-1"  value="ADD">
			</form>
	    </div>
	</div>
</div>


{% endblock %}

templates/question.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
	textarea{
		width: 100%;
		border-radius: 5px; border:1px solid #ddd;
	}
</style>
<div class="appHeader " style="background-color: transparent;box-shadow: none;">
    <div class="left">
        <a href="{% url 'main:my_diary' %}" class="headerButton goBack">
            <ion-icon name="chevron-back-outline" role="img" class="md hydrated" aria-label="chevron back outline"></ion-icon>
        </a>
    </div>
    <div class="pageTitle">
     {{ question.text }}
    </div>
    <div class="right">
        
    </div>
</div>
<div class="section full" style="margin-top: 55px !important">
    <div class="wide-block pt-2 pb-2" style="background-color: transparent;">
        <div class="section-title">Click the button below to start the analyze.</div>
	    <div class="pt-2 pb-2 text-center">
	    	
			<form method="post" action="{% url 'main:submit_answer' %}">
			    {% csrf_token %}
			    <input type="hidden" name="question_id" value="{{ question.id }}">
			    <textarea name="answer">{{ answer.text }}</textarea>
			    <button type="submit" class="btn btn-secondary" style="display: block;background-color: #30C08B !important;border-color:#30C08B !important ">Next</button>
			</form>
	    </div>
    </div>
</div>

{% endblock %}